version: '3'
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: "Pandas"
            POSTGRES_USER: "yuuun"
            POSTGRES_PASSWORD: "avito123"
        ports:
            - '5432:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data